implemented
CBIIT/crdc-datahub-database-drivers pull request #149
Opened 2024-12-03 18:58 UTC by vshand11

Implemented 1) CRDCDH-2009 2) CRDCDH-2060.  These two tasks has overlapping requests and highly related.

2024-12-03 20:05 UTC, knockknockyoo commented on services/user.js
> -        } else if ((typeof(params.organization) !== "undefined" && !params.organization && user[0]?.organization?.orgID)) { // Data Curator should not be assigned any Org
Is this required for the current implementation? **The Data Curator should not be assigned any organization**. It was one of requirements in the past.

2024-12-03 20:08 UTC, knockknockyoo requested changes

2024-12-03 20:08 UTC, knockknockyoo commented on services/user.js
> +        const valid_studies = await this.#findApprovedStudies(params.studies);
Please, change this name convention.

2024-12-03 20:20 UTC, vshand11 commented on services/user.js
> +        const valid_studies = await this.#findApprovedStudies(params.studies);
Updated.

2024-12-03 20:40 UTC, knockknockyoo commented
studies: [String] is optional in the graphql scheme. If **studies** parameter is not included, it will cause unexpected error. We should only store **studies** only if a studies parameter is included.

2024-12-04 19:47 UTC, AustinSMueller approved these changes

2024-12-04 19:47 UTC, merged