Permission Constant
CBIIT/crdc-datahub-database-drivers pull request #159
Opened 2024-12-12 19:55 UTC by knockknockyoo

2024-12-12 21:16 UTC, n2iw requested changes

2024-12-12 21:16 UTC, n2iw commented on constants/user-permission-constants.js
> +            SUBMIT: "data_submission:request_access",
This should be **data_submission:submitted**

2024-12-12 21:16 UTC, n2iw commented on constants/user-permission-constants.js
> +            COMPLETE: "data_submission:complete",
Should be data_submission:completed

2024-12-12 22:00 UTC, knockknockyoo commented on constants/user-permission-constants.js
> +            SUBMIT: "data_submission:request_access",
fixed it.

2024-12-12 22:00 UTC, knockknockyoo commented on constants/user-permission-constants.js
> +            COMPLETE: "data_submission:complete",
fixed it.

2024-12-13 16:06 UTC, n2iw approved these changes
LGTM

2024-12-13 17:14 UTC, merged