CRDCDH-458 Support `dataCommons` assignment
CBIIT/crdc-datahub-database-drivers pull request #48
Opened 2023-10-03 19:31 UTC by amattu2

TODO: description and AuthZ link

* If a user IS a DC_POC the dataCommons field will be updated
* If a user WILL BE (after the update) a DC_POC, the dataCommons field will be updated
* The field is cleared otherwise
* No validation on allowed Data Commons is in the BE. TBD if desired

2023-10-05 20:47 UTC, n2iw requested changes

2023-10-05 20:47 UTC, n2iw commented on services/user.js
> +            if (!params.dataCommons || params.dataCommons.length === 0) {
We should allow client to omit dataCommons parameter, if current role is DC POC and dataCommons has values in the DB.

2023-10-06 17:45 UTC, amattu2 commented on services/user.js
> +            if (!params.dataCommons || params.dataCommons.length === 0) {
Updated to allow for this scenario.

2023-10-06 18:46 UTC, n2iw approved these changes
LGTM

2023-10-06 18:46 UTC, merged